[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 11

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[keyboard]
bindings = [{ key= "Back", mods= "Control", chars= "\u0017"}]

[window]
opacity = 1.0
